CREATE VIEW [CUSTOMER_MASTER_VIEW] AS 
SELECT
  CUSTOMER_MASTER.COMPANY_NO_BOX
  , CUSTOMER_MASTER.TRANSACTION_TYPE
  , CUSTOMER_MASTER.EFFECTIVE_DATE
  , CUSTOMER_MASTER.REQ_SEQ
  , CUSTOMER_MASTER.UPDATE_CONTENT
  , REQUEST_DETAIL.COMPANY_NAME
  , REQUEST_DETAIL.COMPANY_NAME_READING
  , REQUEST_DETAIL.QUOTATION_DATE
  , CUSTOMER_MASTER.CONTRACT_DATE
  , REQUEST_DETAIL.COMPLETION_NOTIFICATION_DATE
  , REQ_ADDRESS1.COMPANY_NAME AS CONTRACTOR_COMPANY_NAME
  , REQ_ADDRESS1.DEPARTMENT_IN_CHARGE AS CONTRACTOR_DEPARTMENT_IN_CHARGE
  , REQ_ADDRESS1.CONTACT_NAME AS CONTRACTOR_CONTACT_NAME
  , REQ_ADDRESS1.CONTACT_NAME_READING AS CONTRACTOR_CONTACT_NAME_READING
  , REQ_ADDRESS1.POSTAL_CODE AS CONTRACTOR_POSTAL_CODE
  , REQ_ADDRESS1.ADDRESS AS CONTRACTOR_ADDRESS
  , REQ_ADDRESS1.ADDRESS_BUILDING AS CONTRACTOR_ADDRESS_BUILDING
  , REQ_ADDRESS1.MAIL_ADDRESS AS CONTRACTOR_MAIL_ADDRESS
  , REQ_ADDRESS1.PHONE_NUMBER AS CONTRACTOR_PHONE_NUMBER
  , REQUEST_DETAIL.BILL_SUPPLIER_NAME
  , REQUEST_DETAIL.BILL_SUPPLIER_NAME_READING
  , REQ_ADDRESS2.COMPANY_NAME AS BILL_COMPANY_NAME
  , REQ_ADDRESS2.DEPARTMENT_IN_CHARGE AS BILL_DEPARTMENT_IN_CHARGE
  , REQ_ADDRESS2.CONTACT_NAME AS BILL_CONTACT_NAME
  , REQ_ADDRESS2.CONTACT_NAME_READING AS BILL_CONTACT_NAME_READING
  , REQ_ADDRESS2.POSTAL_CODE AS BILL_POSTAL_CODE
  , REQ_ADDRESS2.ADDRESS AS BILL_ADDRESS
  , REQ_ADDRESS2.ADDRESS_BUILDING AS BILL_ADDRESS_BUILDING
  , REQ_ADDRESS2.MAIL_ADDRESS AS BILL_MAIL_ADDRESS
  , REQ_ADDRESS2.PHONE_NUMBER AS BILL_PHONE_NUMBER
  , CUSTOMER_MASTER.SPECIAL_NOTES_1
  , CUSTOMER_MASTER.SPECIAL_NOTES_2
  , CUSTOMER_MASTER.SPECIAL_NOTES_3
  , CUSTOMER_MASTER.SPECIAL_NOTES_4
  , CASE 
    WHEN CUSTOMER_MASTER.TRANSACTION_TYPE = 1 
      THEN 12 
    WHEN ( 
      CUSTOMER_MASTER.TRANSACTION_TYPE = 2 
      OR CUSTOMER_MASTER.TRANSACTION_TYPE = 3
    ) 
      THEN 22 
    WHEN (CUSTOMER_MASTER.TRANSACTION_TYPE = 4) 
      THEN 32 
    END BILL_TYPE
  , REQUEST_DETAIL.BILL_METHOD
  , CUSTOMER_MASTER.NCS_CUSTOMER_CODE
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NAME-1]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NUMBER-1]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NAME-2]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NUMBER-2]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NAME-3]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NUMBER-3]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NAME-4]
  , BANK_ACCOUNT_MASTER.[BILL_BANK_ACCOUNT_NUMBER-4]
  , CUSTOMER_MASTER.BILL_BILLING_INTERVAL
  , CUSTOMER_MASTER.BILL_DEPOSIT_RULES
  , ISNULL(CUSTOMER_MASTER.BILL_TRANSFER_FEE, 0) BILL_TRANSFER_FEE
  , ISNULL(CUSTOMER_MASTER.BILL_EXPENSES, 0) BILL_EXPENSES
  , REQUEST_DETAIL.PLAN_AMIGO_CAI
  , REQUEST_DETAIL.PLAN_AMIGO_BIZ
  , REQUEST_DETAIL.BOX_SIZE
  , REQUEST_DETAIL.INITIAL_COST
  , REQUEST_DETAIL.INITIAL_COST_DISCOUNTS
  , REQUEST_DETAIL.INITIAL_COST_INCLUDING_TAX
  , REQUEST_DETAIL.MONTHLY_COST
  , REQUEST_DETAIL.MONTHLY_COST_DISCOUNTS
  , REQUEST_DETAIL.MONTHLY_COST_INCLUDING_TAX
  , REQUEST_DETAIL.YEAR_COST
  , REQUEST_DETAIL.YEAR_COST_DISCOUNTS
  , REQUEST_DETAIL.YEAR_COST_INCLUDING_TAX
  , REQUEST_DETAIL.CONTRACT_PLAN
  , REQUEST_DETAIL.OP_AMIGO_CAI
  , REQUEST_DETAIL.OP_AMIGO_BIZ
  , REQUEST_DETAIL.OP_BOX_SERVER
  , REQUEST_DETAIL.OP_BOX_BROWSER
  , REQUEST_DETAIL.OP_FLAT
  , REQUEST_DETAIL.OP_CLIENT
  , REQUEST_DETAIL.OP_BASIC_SERVICE
  , REQUEST_DETAIL.OP_ADD_SERVICE
  , REQUEST_ID.SOCIOS_USER_FLG
  , CUSTOMER_MASTER.COMPANY_NAME_CHANGED_DATE
  , CUSTOMER_MASTER.PREVIOUS_COMPANY_NAME
  , REQUEST_DETAIL.NML_CODE_NISSAN
  , REQUEST_DETAIL.NML_CODE_NS
  , REQUEST_DETAIL.NML_CODE_JATCO
  , REQUEST_DETAIL.NML_CODE_AK
  , REQUEST_DETAIL.NML_CODE_NK
  , CUSTOMER_MASTER.OBOEGAKI_DATE
  , CUSTOMER_MASTER.CREATED_AT
  , CUSTOMER_MASTER.CREATED_BY
  , CUSTOMER_MASTER.UPDATED_AT
  , CUSTOMER_MASTER.UPDATED_BY 
FROM
  CUSTOMER_MASTER 
  LEFT JOIN BANK_ACCOUNT_MASTER 
    ON CUSTOMER_MASTER.COMPANY_NO_BOX = BANK_ACCOUNT_MASTER.COMPANY_NO_BOX 
    AND CUSTOMER_MASTER.REQ_SEQ = BANK_ACCOUNT_MASTER.REQ_SEQ 
  LEFT JOIN REQUEST_DETAIL 
    ON CUSTOMER_MASTER.COMPANY_NO_BOX = REQUEST_DETAIL.COMPANY_NO_BOX 
    AND CUSTOMER_MASTER.REQ_SEQ = REQUEST_DETAIL.REQ_SEQ 
  LEFT JOIN REQ_ADDRESS AS REQ_ADDRESS1 
    ON CUSTOMER_MASTER.COMPANY_NO_BOX = REQ_ADDRESS1.COMPANY_NO_BOX 
    AND CUSTOMER_MASTER.REQ_SEQ = REQ_ADDRESS1.REQ_SEQ 
    AND REQ_ADDRESS1.TYPE = 1 
    AND REQ_ADDRESS1.REQ_ADDRESS_SEQ = 1 
  LEFT JOIN REQ_ADDRESS AS REQ_ADDRESS2 
    ON CUSTOMER_MASTER.COMPANY_NO_BOX = REQ_ADDRESS2.COMPANY_NO_BOX 
    AND CUSTOMER_MASTER.REQ_SEQ = REQ_ADDRESS2.REQ_SEQ 
    AND REQ_ADDRESS2.TYPE = 2 
    AND REQ_ADDRESS2.REQ_ADDRESS_SEQ = 1 
  LEFT JOIN REQUEST_ID 
    ON CUSTOMER_MASTER.COMPANY_NO_BOX = REQUEST_ID.COMPANY_NO_BOX 
ORDER BY
  CUSTOMER_MASTER.COMPANY_NO_BOX ASC
  , CUSTOMER_MASTER.TRANSACTION_TYPE ASC
  , CUSTOMER_MASTER.EFFECTIVE_DATE DESC OFFSET 0 ROWS