//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoProcessManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Jimugo_Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Jimugo_Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmigoProcessManagement.Properties.Jimugo.Messages", typeof(Jimugo_Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザIDもしくはパスワードが正しくありません。.
        /// </summary>
        internal static string E000WA001 {
            get {
                return ResourceManager.GetString("E000WA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン失敗回数が上限に達しました。{0}分待ってから再度ログインしてください。.
        /// </summary>
        internal static string E000WA002 {
            get {
                return ResourceManager.GetString("E000WA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当システムに登録されていないユーザーIDです。\nユーザーIDが不明な場合は、\nお手数ですがサポートまでお問い合わせください。.
        /// </summary>
        internal static string E000WA003 {
            get {
                return ResourceManager.GetString("E000WA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は 8～100文字で設定してください。.
        /// </summary>
        internal static string E000WA004 {
            get {
                return ResourceManager.GetString("E000WA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は半角の英字・数字・記号で入力してください。.
        /// </summary>
        internal static string E000WA005 {
            get {
                return ResourceManager.GetString("E000WA005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーIDと同一のパスワードは設定できません。.
        /// </summary>
        internal static string E000WA006 {
            get {
                return ResourceManager.GetString("E000WA006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に同じ文字を連続3回含めることはできません。.
        /// </summary>
        internal static string E000WA007 {
            get {
                return ResourceManager.GetString("E000WA007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は「アルファベット大文字」「アルファベット小文字」「数字」「記号」の4種類のうち、3種類を利用してください。.
        /// </summary>
        internal static string E000WA008 {
            get {
                return ResourceManager.GetString("E000WA008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの有効期限が過ぎています。パスワードを変更してください。.
        /// </summary>
        internal static string E000WA009 {
            get {
                return ResourceManager.GetString("E000WA009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のパスワードが正しくありません。.
        /// </summary>
        internal static string E000WA010 {
            get {
                return ResourceManager.GetString("E000WA010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初回のログインです。パスワードを変更してください。.
        /// </summary>
        internal static string E000WA011 {
            get {
                return ResourceManager.GetString("E000WA011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードが確認用欄と一致しません。.
        /// </summary>
        internal static string E000WA012 {
            get {
                return ResourceManager.GetString("E000WA012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のパスワードと同じパスワードには変更できません。.
        /// </summary>
        internal static string E000WA013 {
            get {
                return ResourceManager.GetString("E000WA013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社番号+BOXまたはパスワードが正しくありません。.
        /// </summary>
        internal static string E000WA014 {
            get {
                return ResourceManager.GetString("E000WA014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの保存に失敗しました。ファイル名：{0}.
        /// </summary>
        internal static string E000WB001 {
            get {
                return ResourceManager.GetString("E000WB001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 利用申請の更新が失敗しました。.
        /// </summary>
        internal static string E000WB002 {
            get {
                return ResourceManager.GetString("E000WB002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳票履歴の登録が失敗しました。.
        /// </summary>
        internal static string E000WB003 {
            get {
                return ResourceManager.GetString("E000WB003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 異常終了。会社番号+BOXを紐づけるクライアント証明書が取得できません。.
        /// </summary>
        internal static string E000WB004 {
            get {
                return ResourceManager.GetString("E000WB004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 異常終了。クライアント証明書の更新が失敗しました。.
        /// </summary>
        internal static string E000WB005 {
            get {
                return ResourceManager.GetString("E000WB005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了通知ファイルのバックアップが失敗しました。.
        /// </summary>
        internal static string E000WB006 {
            get {
                return ResourceManager.GetString("E000WB006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの圧縮が失敗しました。.
        /// </summary>
        internal static string E000WB007 {
            get {
                return ResourceManager.GetString("E000WB007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了通知メールの送信が失敗しました。.
        /// </summary>
        internal static string E000WB008 {
            get {
                return ResourceManager.GetString("E000WB008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了通知PWメールの送信が失敗しました。.
        /// </summary>
        internal static string E000WB009 {
            get {
                return ResourceManager.GetString("E000WB009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録完了通知が済んでいないため、覚書データのダウンロードは出来ません。.
        /// </summary>
        internal static string E000WB010 {
            get {
                return ResourceManager.GetString("E000WB010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システム設定状況が依頼中以降の場合は、利用申請書の取消が出来ません。.
        /// </summary>
        internal static string E000WB011 {
            get {
                return ResourceManager.GetString("E000WB011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量初期値には選択/数量が数量の場合に設定できます。.
        /// </summary>
        internal static string E000WB012 {
            get {
                return ResourceManager.GetString("E000WB012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIアカウントは、既に使用されています。.
        /// </summary>
        internal static string E000WB013 {
            get {
                return ResourceManager.GetString("E000WB013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集状態の行が存在します。設定完了が出来ません。.
        /// </summary>
        internal static string E000WB014 {
            get {
                return ResourceManager.GetString("E000WB014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システム設定状況が依頼中以降の場合は、承認解除が出来ません。.
        /// </summary>
        internal static string E000WB015 {
            get {
                return ResourceManager.GetString("E000WB015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF形式のファイルのみ登録が可能です。\nPDFファイルを選択して下さい。.
        /// </summary>
        internal static string E000WB016 {
            get {
                return ResourceManager.GetString("E000WB016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 利用申請見積の更新が失敗しました。.
        /// </summary>
        internal static string E000WB017 {
            get {
                return ResourceManager.GetString("E000WB017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールの作成が失敗しました。.
        /// </summary>
        internal static string E000WB018 {
            get {
                return ResourceManager.GetString("E000WB018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客マスタの登録が失敗しました。.
        /// </summary>
        internal static string E000WB019 {
            get {
                return ResourceManager.GetString("E000WB019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が更新されています。\nもう一度プレビューボタンを押下してください。.
        /// </summary>
        internal static string E000WB033 {
            get {
                return ResourceManager.GetString("E000WB033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}用の見積情報が無いため、帳票を作成することが出来ません。.
        /// </summary>
        internal static string E000WB034 {
            get {
                return ResourceManager.GetString("E000WB034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象請求年月の請求データが存在しません。請求データ作成ボタンにてデータを作成後にお試しください。.
        /// </summary>
        internal static string E000WC002 {
            get {
                return ResourceManager.GetString("E000WC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求データの削除に失敗しました。処理を終了します。既存の請求データは元の状態で残っています。.
        /// </summary>
        internal static string E000WC003 {
            get {
                return ResourceManager.GetString("E000WC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求データの更新に失敗しました。処理を終了します。既存の請求データは更新前の状態で残っています。.
        /// </summary>
        internal static string E000WC004 {
            get {
                return ResourceManager.GetString("E000WC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求リストBASEの作成が失敗しました。.
        /// </summary>
        internal static string E000WC005 {
            get {
                return ResourceManager.GetString("E000WC005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必須入力です。.
        /// </summary>
        internal static string E000ZZ001 {
            get {
                return ResourceManager.GetString("E000ZZ001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの型が間違っています。.
        /// </summary>
        internal static string E000ZZ002 {
            get {
                return ResourceManager.GetString("E000ZZ002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青色の箇所のいずれかに入力が必要です。.
        /// </summary>
        internal static string E000ZZ003 {
            get {
                return ResourceManager.GetString("E000ZZ003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラインを選択してください。.
        /// </summary>
        internal static string E000ZZ004 {
            get {
                return ResourceManager.GetString("E000ZZ004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桁数オーバーです。.
        /// </summary>
        internal static string E000ZZ005 {
            get {
                return ResourceManager.GetString("E000ZZ005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桁数が足りません。.
        /// </summary>
        internal static string E000ZZ006 {
            get {
                return ResourceManager.GetString("E000ZZ006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数値を入力してください。.
        /// </summary>
        internal static string E000ZZ007 {
            get {
                return ResourceManager.GetString("E000ZZ007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部品番号は10桁または12桁で入力して下さい。.
        /// </summary>
        internal static string E000ZZ008 {
            get {
                return ResourceManager.GetString("E000ZZ008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}には、YYYYMMDDで設定して下さい。.
        /// </summary>
        internal static string E000ZZ009 {
            get {
                return ResourceManager.GetString("E000ZZ009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に年月日が入力されていません。.
        /// </summary>
        internal static string E000ZZ010 {
            get {
                return ResourceManager.GetString("E000ZZ010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力値が不正です。.
        /// </summary>
        internal static string E000ZZ013 {
            get {
                return ResourceManager.GetString("E000ZZ013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限がないため更新できません。.
        /// </summary>
        internal static string E000ZZ014 {
            get {
                return ResourceManager.GetString("E000ZZ014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要求の形式が正しくありません。.
        /// </summary>
        internal static string E000ZZ015 {
            get {
                return ResourceManager.GetString("E000ZZ015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この操作を実行する権限がありません。.
        /// </summary>
        internal static string E000ZZ016 {
            get {
                return ResourceManager.GetString("E000ZZ016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保守機能の編集権限がありません。.
        /// </summary>
        internal static string E000ZZ017 {
            get {
                return ResourceManager.GetString("E000ZZ017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページの有効期限が切れました。お手数ですが、ホーム画面からやり直してください。.
        /// </summary>
        internal static string E000ZZ018 {
            get {
                return ResourceManager.GetString("E000ZZ018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードに失敗しました。.
        /// </summary>
        internal static string E000ZZ019 {
            get {
                return ResourceManager.GetString("E000ZZ019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードに失敗しました。.
        /// </summary>
        internal static string E000ZZ020 {
            get {
                return ResourceManager.GetString("E000ZZ020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セッションがタイムアウトしました。お手数ですが、再度ログインしてください。.
        /// </summary>
        internal static string E000ZZ021 {
            get {
                return ResourceManager.GetString("E000ZZ021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムエラーが発生しました。.
        /// </summary>
        internal static string E000ZZ022 {
            get {
                return ResourceManager.GetString("E000ZZ022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択されたファイルは{0}MBを超えています。アップロードできません。.
        /// </summary>
        internal static string E000ZZ024 {
            get {
                return ResourceManager.GetString("E000ZZ024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バッチ連携中のため編集はできません。しばらく経ってからやり直してください。発行No={0}.
        /// </summary>
        internal static string E000ZZ026 {
            get {
                return ResourceManager.GetString("E000ZZ026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バッチ連携中のため編集はできません。しばらく経ってからやり直してください。納品チケットNo={0}.
        /// </summary>
        internal static string E000ZZ027 {
            get {
                return ResourceManager.GetString("E000ZZ027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録できません。同じ{0}は使用できません。.
        /// </summary>
        internal static string E000ZZ028 {
            get {
                return ResourceManager.GetString("E000ZZ028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が登録されていない為、メール送信できません。.
        /// </summary>
        internal static string E000ZZ029 {
            get {
                return ResourceManager.GetString("E000ZZ029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録できません。{0}が{1}より過去日になっています。.
        /// </summary>
        internal static string E000ZZ030 {
            get {
                return ResourceManager.GetString("E000ZZ030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録できません。同じ{0}の期間が重複しています。.
        /// </summary>
        internal static string E000ZZ031 {
            get {
                return ResourceManager.GetString("E000ZZ031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除できません。廃止されているデータのみ削除できます。.
        /// </summary>
        internal static string E000ZZ032 {
            get {
                return ResourceManager.GetString("E000ZZ032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除できません。同じ{0}は利用申請テーブルで既に使用されています。.
        /// </summary>
        internal static string E000ZZ033 {
            get {
                return ResourceManager.GetString("E000ZZ033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数行チェックされています。.
        /// </summary>
        internal static string E000ZZ034 {
            get {
                return ResourceManager.GetString("E000ZZ034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認できません。申請状況が申請中ではありません。.
        /// </summary>
        internal static string E000ZZ035 {
            get {
                return ResourceManager.GetString("E000ZZ035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認解除できません。申請状況が承認済ではありません。.
        /// </summary>
        internal static string E000ZZ036 {
            get {
                return ResourceManager.GetString("E000ZZ036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承認解除できません。既に見積発行済です。.
        /// </summary>
        internal static string E000ZZ037 {
            get {
                return ResourceManager.GetString("E000ZZ037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録できません。既に同じ{0}が登録されています。.
        /// </summary>
        internal static string E000ZZ038 {
            get {
                return ResourceManager.GetString("E000ZZ038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}にはスペース、または*を設定する必要があります。.
        /// </summary>
        internal static string E000ZZ039 {
            get {
                return ResourceManager.GetString("E000ZZ039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインタイプにはA,B,C,D,E,Gのいずれかを設定する必要があります。.
        /// </summary>
        internal static string E000ZZ040 {
            get {
                return ResourceManager.GetString("E000ZZ040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール送信処理が異常終了しました。.
        /// </summary>
        internal static string E000ZZ041 {
            get {
                return ResourceManager.GetString("E000ZZ041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIアカウント候補テーブルに未使用のレコードがありません。.
        /// </summary>
        internal static string E000ZZ042 {
            get {
                return ResourceManager.GetString("E000ZZ042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以前に使用されたことがあるEDIアカウントのため、使用できません。.
        /// </summary>
        internal static string E000ZZ043 {
            get {
                return ResourceManager.GetString("E000ZZ043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バッチ処理が異常終了しました。.
        /// </summary>
        internal static string E000ZZ044 {
            get {
                return ResourceManager.GetString("E000ZZ044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が{1}より過去日になっています。.
        /// </summary>
        internal static string E000ZZ045 {
            get {
                return ResourceManager.GetString("E000ZZ045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}には{1}以上を設定する必要があります。.
        /// </summary>
        internal static string E000ZZ046 {
            get {
                return ResourceManager.GetString("E000ZZ046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同じ担当者、メールアドレス、電話番号は既に使用されています。.
        /// </summary>
        internal static string E000ZZ047 {
            get {
                return ResourceManager.GetString("E000ZZ047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先_銀行振込手数料は0以下の値を設定する必要があります。.
        /// </summary>
        internal static string E000ZZ048 {
            get {
                return ResourceManager.GetString("E000ZZ048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求先_諸経費は0以上の値を設定する必要があります。.
        /// </summary>
        internal static string E000ZZ049 {
            get {
                return ResourceManager.GetString("E000ZZ049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同じ「会社番号+BOX, 取引区分, 発効日」は使用できません。.
        /// </summary>
        internal static string E000ZZ050 {
            get {
                return ResourceManager.GetString("E000ZZ050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は必須入力です。.
        /// </summary>
        internal static string E000ZZ051 {
            get {
                return ResourceManager.GetString("E000ZZ051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレス、電話番号のどちらかは必須入力です。.
        /// </summary>
        internal static string E000ZZ052 {
            get {
                return ResourceManager.GetString("E000ZZ052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会社番号+BOXをクライアント証明書と紐づけました。クライアント証明書一覧画面でご確認ください。.
        /// </summary>
        internal static string I000WB001 {
            get {
                return ResourceManager.GetString("I000WB001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前回プレビュー時から以下の項目が変更されています。\n再度プレビューボタンを押下し、内容を確認してください。\n項目：{0}.
        /// </summary>
        internal static string I000WB002 {
            get {
                return ResourceManager.GetString("I000WB002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールを作成しますか？.
        /// </summary>
        internal static string I000WB003 {
            get {
                return ResourceManager.GetString("I000WB003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「クライアント証明書の有効期限(To)」は「クライアント証明書の有効期限(From)」より未来の日付にして下さい。.
        /// </summary>
        internal static string I000WB004 {
            get {
                return ResourceManager.GetString("I000WB004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客マスタが同一利用申請連番で2行以上取得されました。.
        /// </summary>
        internal static string I000WB005 {
            get {
                return ResourceManager.GetString("I000WB005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に請求リストデータが作成済みですが再作成しますか？.
        /// </summary>
        internal static string I000WC001 {
            get {
                return ResourceManager.GetString("I000WC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求データの作成が正常に終了しました。{0}件.
        /// </summary>
        internal static string I000WC002 {
            get {
                return ResourceManager.GetString("I000WC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録しますか？.
        /// </summary>
        internal static string I000ZZ001 {
            get {
                return ResourceManager.GetString("I000ZZ001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更内容が破棄されます。宜しいですか？.
        /// </summary>
        internal static string I000ZZ002 {
            get {
                return ResourceManager.GetString("I000ZZ002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当データは既に登録されています。.
        /// </summary>
        internal static string I000ZZ003 {
            get {
                return ResourceManager.GetString("I000ZZ003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当データが存在しません。.
        /// </summary>
        internal static string I000ZZ004 {
            get {
                return ResourceManager.GetString("I000ZZ004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当データは他ユーザーにより更新されました。最初からやり直してください。.
        /// </summary>
        internal static string I000ZZ005 {
            get {
                return ResourceManager.GetString("I000ZZ005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当データは他ユーザーにより削除されました。.
        /// </summary>
        internal static string I000ZZ006 {
            get {
                return ResourceManager.GetString("I000ZZ006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新処理が正常に終了しました。.
        /// </summary>
        internal static string I000ZZ007 {
            get {
                return ResourceManager.GetString("I000ZZ007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除しますか？.
        /// </summary>
        internal static string I000ZZ008 {
            get {
                return ResourceManager.GetString("I000ZZ008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除しました。.
        /// </summary>
        internal static string I000ZZ009 {
            get {
                return ResourceManager.GetString("I000ZZ009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新しますか?.
        /// </summary>
        internal static string I000ZZ010 {
            get {
                return ResourceManager.GetString("I000ZZ010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録しました。.
        /// </summary>
        internal static string I000ZZ011 {
            get {
                return ResourceManager.GetString("I000ZZ011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信に成功しました。.
        /// </summary>
        internal static string I000ZZ012 {
            get {
                return ResourceManager.GetString("I000ZZ012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワンタイムパスワードの再発行を行いますか？.
        /// </summary>
        internal static string I000ZZ013 {
            get {
                return ResourceManager.GetString("I000ZZ013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のユーザーにより更新されました。.
        /// </summary>
        internal static string I000ZZ014 {
            get {
                return ResourceManager.GetString("I000ZZ014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール送信処理が正常に終了しました。.
        /// </summary>
        internal static string I000ZZ015 {
            get {
                return ResourceManager.GetString("I000ZZ015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}処理が正常に終了しました。.
        /// </summary>
        internal static string I000ZZ016 {
            get {
                return ResourceManager.GetString("I000ZZ016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バッチ処理が完了しました。.
        /// </summary>
        internal static string I000ZZ017 {
            get {
                return ResourceManager.GetString("I000ZZ017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string I000ZZ018 {
            get {
                return ResourceManager.GetString("I000ZZ018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール送信しますか？.
        /// </summary>
        internal static string I000ZZ019 {
            get {
                return ResourceManager.GetString("I000ZZ019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール送信中です。.
        /// </summary>
        internal static string I000ZZ020 {
            get {
                return ResourceManager.GetString("I000ZZ020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集行が存在している場合は編集状態が破棄されます。よろしいですか？.
        /// </summary>
        internal static string I000ZZ021 {
            get {
                return ResourceManager.GetString("I000ZZ021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール作成処理が正常に終了しました。.
        /// </summary>
        internal static string I000ZZ022 {
            get {
                return ResourceManager.GetString("I000ZZ022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインしました。会社番号＋BOX={0}.
        /// </summary>
        internal static string I199WA001 {
            get {
                return ResourceManager.GetString("I199WA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン失敗回数が上限に達しました。.
        /// </summary>
        internal static string I199WA002 {
            get {
                return ResourceManager.GetString("I199WA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クライアント端末情報 - 会社番号＋BOX={0},ユーザーエージェント={1}.
        /// </summary>
        internal static string I199WA006 {
            get {
                return ResourceManager.GetString("I199WA006", resourceCulture);
            }
        }
    }
}
