//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoPapaerWorkProcessSystem.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmigoPapaerWorkProcessSystem.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力フォルダにデータがありません.
        /// </summary>
        internal static string BatchProcessInp_w0003 {
            get {
                return ResourceManager.GetString("BatchProcessInp.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_all {
            get {
                object obj = ResourceManager.GetObject("check_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返金処理が完了しました。.
        /// </summary>
        internal static string ChkUmiCmp_i0006 {
            get {
                return ResourceManager.GetString("ChkUmiCmp.i0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返金処理を実行してもよいですか。.
        /// </summary>
        internal static string ChkUmiCnf_i0005 {
            get {
                return ResourceManager.GetString("ChkUmiCnf.i0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日はYYYY/MM/DDで入力して下さい。.
        /// </summary>
        internal static string ChkUmiInp_w0001 {
            get {
                return ResourceManager.GetString("ChkUmiInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日を入力して下さい。.
        /// </summary>
        internal static string ChkUmiInp_w0002 {
            get {
                return ResourceManager.GetString("ChkUmiInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日(FROM)を入力して下さい。.
        /// </summary>
        internal static string ChkUmiInp_w0003 {
            get {
                return ResourceManager.GetString("ChkUmiInp.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日(FROM)と引当日(TO)を確認して下さい。.
        /// </summary>
        internal static string ChkUmiInp_w0004 {
            get {
                return ResourceManager.GetString("ChkUmiInp.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string ChkUmiInp_w0007 {
            get {
                return ResourceManager.GetString("ChkUmiInp.w0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数行が選択されています。1行のみを選択して下さい。.
        /// </summary>
        internal static string ChkUmiInp_w0008 {
            get {
                return ResourceManager.GetString("ChkUmiInp.w0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo外データに移動しました。.
        /// </summary>
        internal static string CnfAmiCmp_i0001 {
            get {
                return ResourceManager.GetString("CnfAmiCmp.i0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string CnfAmiInp_w0004 {
            get {
                return ResourceManager.GetString("CnfAmiInp.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数行が選択されています。1行のみを選択して下さい。.
        /// </summary>
        internal static string CnfAmiInp_w0005 {
            get {
                return ResourceManager.GetString("CnfAmiInp.w0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string CnfAmiRpt_w0002 {
            get {
                return ResourceManager.GetString("CnfAmiRpt.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが0件の行が選択されています。.
        /// </summary>
        internal static string CnfAmiRpt_w0003 {
            get {
                return ResourceManager.GetString("CnfAmiRpt.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string CnfBtiInp_w0001 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数行が選択されています。1行のみを選択して下さい。.
        /// </summary>
        internal static string CnfBtiInp_w0002 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取込日はYYYY/MM/DDで入力して下さい。.
        /// </summary>
        internal static string CnfBtiInp_w0003 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取込日を入力して下さい。.
        /// </summary>
        internal static string CnfBtiInp_w0004 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取込日(FROM)を入力して下さい。.
        /// </summary>
        internal static string CnfBtiInp_w0005 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取込日(FROM)と取込日(TO)を確認して下さい。.
        /// </summary>
        internal static string CnfBtiInp_w0006 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが0件の行が選択されています。.
        /// </summary>
        internal static string CnfBtiInp_w0008 {
            get {
                return ResourceManager.GetString("CnfBtiInp.w0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string CnfBtiRpt_w0007 {
            get {
                return ResourceManager.GetString("CnfBtiRpt.w0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日はYYYY/MM/DDで入力して下さい。.
        /// </summary>
        internal static string CnfCmpInp_w0001 {
            get {
                return ResourceManager.GetString("CnfCmpInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日を入力して下さい。.
        /// </summary>
        internal static string CnfCmpInp_w0002 {
            get {
                return ResourceManager.GetString("CnfCmpInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日(FROM)を入力して下さい。.
        /// </summary>
        internal static string CnfCmpInp_w0003 {
            get {
                return ResourceManager.GetString("CnfCmpInp.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日(FROM)と引当日(TO)を確認して下さい。.
        /// </summary>
        internal static string CnfCmpInp_w0004 {
            get {
                return ResourceManager.GetString("CnfCmpInp.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string CnfCmpRpt_w0005 {
            get {
                return ResourceManager.GetString("CnfCmpRpt.w0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経理CSVの出力が完了しました。.
        /// </summary>
        internal static string CnfDtlCmp_i0005 {
            get {
                return ResourceManager.GetString("CnfDtlCmp.i0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当をキャンセルしました。.
        /// </summary>
        internal static string CnfDtlCmp_i0007 {
            get {
                return ResourceManager.GetString("CnfDtlCmp.i0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日はYYYY/MM/DDで入力して下さい。.
        /// </summary>
        internal static string CnfDtlInp_w0001 {
            get {
                return ResourceManager.GetString("CnfDtlInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日を入力して下さい。.
        /// </summary>
        internal static string CnfDtlInp_w0002 {
            get {
                return ResourceManager.GetString("CnfDtlInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日(FROM)を入力して下さい。.
        /// </summary>
        internal static string CnfDtlInp_w0003 {
            get {
                return ResourceManager.GetString("CnfDtlInp.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日(FROM)と引当日(TO)を確認して下さい。.
        /// </summary>
        internal static string CnfDtlInp_w0004 {
            get {
                return ResourceManager.GetString("CnfDtlInp.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string CnfDtlInp_w0006 {
            get {
                return ResourceManager.GetString("CnfDtlInp.w0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードするデータが見つかりません。.
        /// </summary>
        internal static string CnfDtlRpt_w0008 {
            get {
                return ResourceManager.GetString("CnfDtlRpt.w0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigoデータに移動しました。.
        /// </summary>
        internal static string CnfNoaCmp_i0005 {
            get {
                return ResourceManager.GetString("CnfNoaCmp.i0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string CnfNoaInp_w0001 {
            get {
                return ResourceManager.GetString("CnfNoaInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数行が選択されています。1行のみを選択して下さい。.
        /// </summary>
        internal static string CnfNoaInp_w0002 {
            get {
                return ResourceManager.GetString("CnfNoaInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string CnfNoaRpt_w0003 {
            get {
                return ResourceManager.GetString("CnfNoaRpt.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顧客マスタに取引先会社名が存在しません。.
        /// </summary>
        internal static string CnfNoaRpt_w0004 {
            get {
                return ResourceManager.GetString("CnfNoaRpt.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データが0件の行が選択されています。.
        /// </summary>
        internal static string CnfNoaRpt_w0006 {
            get {
                return ResourceManager.GetString("CnfNoaRpt.w0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to のうちだけが移動されます。.
        /// </summary>
        internal static string CnfNoaRpt_w0007 {
            get {
                return ResourceManager.GetString("CnfNoaRpt.w0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザID又はパスワードが正しくありません.
        /// </summary>
        internal static string DpMenuInp_w0002 {
            get {
                return ResourceManager.GetString("DpMenuInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-ID / Password を入力して下さい。.
        /// </summary>
        internal static string DpMenuInp_w0003 {
            get {
                return ResourceManager.GetString("DpMenuInp.w0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string DpMenuRpt_w0001 {
            get {
                return ResourceManager.GetString("DpMenuRpt.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プログラムは既に実行されています。.
        /// </summary>
        internal static string GnmsgRpt_i0005 {
            get {
                return ResourceManager.GetString("GnmsgRpt.i0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 問題が発生しました。.
        /// </summary>
        internal static string GnmsgRpt_s0001 {
            get {
                return ResourceManager.GetString("GnmsgRpt.s0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバー接続タイムアウト。.
        /// </summary>
        internal static string GnmsgRpt_s0002 {
            get {
                return ResourceManager.GetString("GnmsgRpt.s0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インターネットに接続されていません。.
        /// </summary>
        internal static string GnmsgRpt_s0003 {
            get {
                return ResourceManager.GetString("GnmsgRpt.s0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プログラムが見つかりません。.
        /// </summary>
        internal static string GnmsgRpt_s0004 {
            get {
                return ResourceManager.GetString("GnmsgRpt.s0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行振込情報取込処理が完了しました。.
        /// </summary>
        internal static string ImpDepCmp_i0003 {
            get {
                return ResourceManager.GetString("ImpDepCmp.i0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振込入金明細が存在しません。.
        /// </summary>
        internal static string ImpDepRpt_w0001 {
            get {
                return ResourceManager.GetString("ImpDepRpt.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振込入金明細の移動に失敗しました。.
        /// </summary>
        internal static string ImpDepRpt_w0002 {
            get {
                return ResourceManager.GetString("ImpDepRpt.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 突合せ処理が完了しました。.
        /// </summary>
        internal static string MtcInvCmp_i0003 {
            get {
                return ResourceManager.GetString("MtcInvCmp.i0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録が完了しました。.
        /// </summary>
        internal static string RstDepCmp_i0003 {
            get {
                return ResourceManager.GetString("RstDepCmp.i0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to を出力しました。.
        /// </summary>
        internal static string RstDepCmp_i0004 {
            get {
                return ResourceManager.GetString("RstDepCmp.i0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索条件を入力して下さい。.
        /// </summary>
        internal static string RstDepInp_w0001 {
            get {
                return ResourceManager.GetString("RstDepInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string RstDepInp_w0002 {
            get {
                return ResourceManager.GetString("RstDepInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力する年月は1か所にして下さい。.
        /// </summary>
        internal static string RstDepInp_w0005 {
            get {
                return ResourceManager.GetString("RstDepInp.w0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必ず1か所の年月を入力して下さい。.
        /// </summary>
        internal static string RstDepInp_w0006 {
            get {
                return ResourceManager.GetString("RstDepInp.w0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付フィールドをYYYY / MMの形式で入力してください。.
        /// </summary>
        internal static string RstDepInp_w0008 {
            get {
                return ResourceManager.GetString("RstDepInp.w0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引当日はYYYY/MM/DDで入力して下さい。.
        /// </summary>
        internal static string RstDepInp_w0011 {
            get {
                return ResourceManager.GetString("RstDepInp.w0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索日付を正しく入力して下さい。.
        /// </summary>
        internal static string RstDepInp_w0012 {
            get {
                return ResourceManager.GetString("RstDepInp.w0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数行が選択されています。1行のみを選択して下さい。.
        /// </summary>
        internal static string RstDepInp_w0016 {
            get {
                return ResourceManager.GetString("RstDepInp.w0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このデータは手動引当出来ません。.
        /// </summary>
        internal static string RstDepRpt_i0013 {
            get {
                return ResourceManager.GetString("RstDepRpt.i0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このデータは引当完了出来ません。.
        /// </summary>
        internal static string RstDepRpt_i0014 {
            get {
                return ResourceManager.GetString("RstDepRpt.i0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このデータは引当完了の取消は出来ません。.
        /// </summary>
        internal static string RstDepRpt_i0015 {
            get {
                return ResourceManager.GetString("RstDepRpt.i0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードするデータが見つかりません。.
        /// </summary>
        internal static string RstDepRpt_w0009 {
            get {
                return ResourceManager.GetString("RstDepRpt.w0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効なデータを入力してください。.
        /// </summary>
        internal static string RstDepRpt_w0010 {
            get {
                return ResourceManager.GetString("RstDepRpt.w0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uncheck_all {
            get {
                object obj = ResourceManager.GetObject("uncheck_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更が完了しました。.
        /// </summary>
        internal static string UpdCumCmp_i0003 {
            get {
                return ResourceManager.GetString("UpdCumCmp.i0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索条件を入力して下さい。.
        /// </summary>
        internal static string UpdCumInp_w0001 {
            get {
                return ResourceManager.GetString("UpdCumInp.w0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行選択をして下さい。.
        /// </summary>
        internal static string UpdCumInp_w0002 {
            get {
                return ResourceManager.GetString("UpdCumInp.w0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に起動中です。.
        /// </summary>
        internal static string UpdCumRpt_w0004 {
            get {
                return ResourceManager.GetString("UpdCumRpt.w0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効なデータを入力してください。.
        /// </summary>
        internal static string UpdCumRpt_w0005 {
            get {
                return ResourceManager.GetString("UpdCumRpt.w0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀行口座名が一意ではありません。.
        /// </summary>
        internal static string UpdCumRpt_w0006 {
            get {
                return ResourceManager.GetString("UpdCumRpt.w0006", resourceCulture);
            }
        }
    }
}
