//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoPaperWorkProcessSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public global::MetroFramework.MetroThemeStyle Theme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::MetroFramework.MetroColorStyle Style {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["Style"]));
            }
            set {
                this["Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 64")]
        public global::System.Drawing.Color GridHeaderColor {
            get {
                return ((global::System.Drawing.Color)(this["GridHeaderColor"]));
            }
            set {
                this["GridHeaderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color GridHeaderFontColor {
            get {
                return ((global::System.Drawing.Color)(this["GridHeaderFontColor"]));
            }
            set {
                this["GridHeaderFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_38.asmx/getCustomerList?COMPANY_NAME=@COMPANY_NAME&COMP" +
            "ANY_NAME_READING=@COMPANY_READING&BILL_COMPANY_NAME=@BILL_COMPANY_NAME&COMPANY_N" +
            "O_BOX=@COMPANY_NO_BOX&ACCOUNT_NAME=@ACCOUNT_NAME")]
        public string CustomerList {
            get {
                return ((string)(this["CustomerList"]));
            }
            set {
                this["CustomerList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_38.asmx/UpdateCustomer")]
        public string CustomerUpdate {
            get {
                return ((string)(this["CustomerUpdate"]));
            }
            set {
                this["CustomerUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_31.asmx/ConfirmationOfTransfer?strFromDate=@FromDate&st" +
            "rToDate=@ToDate")]
        public string GetBankTR {
            get {
                return ((string)(this["GetBankTR"]));
            }
            set {
                this["GetBankTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_33.asmx/ConfirmationOfTransfer_NonAmigo?strDTMID=@DTMID" +
            "")]
        public string NonAmigo_BankTR {
            get {
                return ((string)(this["NonAmigo_BankTR"]));
            }
            set {
                this["NonAmigo_BankTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_32.asmx/ConfirmationOfTransfer_Amigo?strDTMID=@DTMID")]
        public string Amigo_BankTR {
            get {
                return ((string)(this["Amigo_BankTR"]));
            }
            set {
                this["Amigo_BankTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_32.asmx/ConvertAmigoToNonAmigo")]
        public string AmigoToNonAmigo {
            get {
                return ((string)(this["AmigoToNonAmigo"]));
            }
            set {
                this["AmigoToNonAmigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_33.asmx/ConvertNonAmigoToAmigo")]
        public string NonAmigoToAmigo {
            get {
                return ((string)(this["NonAmigoToAmigo"]));
            }
            set {
                this["NonAmigoToAmigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_34.asmx/ConfirmOfComparisonResult?strFromDate=@FromDate" +
            "&strToDate=@ToDate")]
        public string ConfirmOfComparisonResult {
            get {
                return ((string)(this["ConfirmOfComparisonResult"]));
            }
            set {
                this["ConfirmOfComparisonResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_36.asmx/GetUnmatchInvoice?strFromDate=@FromDate&strToDa" +
            "te=@ToDate")]
        public string GetUnmatchInvoice {
            get {
                return ((string)(this["GetUnmatchInvoice"]));
            }
            set {
                this["GetUnmatchInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_35.asmx/GetMatchInvoice?strFromDate=@FromDate&strToDate" +
            "=@ToDate&strNoReserved=@NoReserved")]
        public string GetMatchInvoice {
            get {
                return ((string)(this["GetMatchInvoice"]));
            }
            set {
                this["GetMatchInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_35.asmx/CancelAllocation")]
        public string CancelAllocation {
            get {
                return ((string)(this["CancelAllocation"]));
            }
            set {
                this["CancelAllocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_36.asmx/RefundProcess?SEQID=@SEQID")]
        public string RefundProcess {
            get {
                return ((string)(this["RefundProcess"]));
            }
            set {
                this["RefundProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/opt_37.asmx/GetDataFor37?TRANSACTION_TYPE=@TRANSACTION_TYPE&FROM_YEAR_MONTH=@FROM_YEAR_MONTH&TO_YEAR_MONTH=@TO_YEAR_MONTH&FROM_STATUS_PLAN_DEPOSIT_YYMM=@FROM_STATUS_PLAN_DEPOSIT_YYMM&TO_STATUS_PLAN_DEPOSIT_YYMM=@TO_STATUS_PLAN_DEPOSIT_YYMM&FROM_STATUS_ACTUAL_DEPOSIT_DATE=@FROM_STATUS_ACTUAL_DEPOSIT_DATE&TO_STATUS_ACTUAL_DEPOSIT_DATE=@TO_STATUS_ACTUAL_DEPOSIT_DATE&DEPOSIT_RULE=@DEPOSIT_RULE&WITH_OR_WITHOUT_PAYMENT=@WITH_OR_WITHOUT_PAYMENT&BILL_SUPPLIER_NAME=@BILL_SUPPLIER_NAME")]
        public string GetDataForGrid37 {
            get {
                return ((string)(this["GetDataForGrid37"]));
            }
            set {
                this["GetDataForGrid37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_37.asmx/UpdateInvoice")]
        public string UpdateInvoice {
            get {
                return ((string)(this["UpdateInvoice"]));
            }
            set {
                this["UpdateInvoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_35.asmx/GetAccountingCSV?strFromDate=@FromDate&strToDat" +
            "e=@ToDate")]
        public string Get35_AccountingCSV {
            get {
                return ((string)(this["Get35_AccountingCSV"]));
            }
            set {
                this["Get35_AccountingCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/opt_37.asmx/Scheduled_Payment?TRANSACTION_TYPE=@TRANSACTION_TYPE&FROM_YEAR_MONTH=@FROM_YEAR_MONTH&TO_YEAR_MONTH=@TO_YEAR_MONTH&FROM_STATUS_PLAN_DEPOSIT_YYMM=@FROM_STATUS_PLAN_DEPOSIT_YYMM&TO_STATUS_PLAN_DEPOSIT_YYMM=@TO_STATUS_PLAN_DEPOSIT_YYMM&FROM_STATUS_ACTUAL_DEPOSIT_DATE=@FROM_STATUS_ACTUAL_DEPOSIT_DATE&TO_STATUS_ACTUAL_DEPOSIT_DATE=@TO_STATUS_ACTUAL_DEPOSIT_DATE&DEPOSIT_RULE=@DEPOSIT_RULE&WITH_OR_WITHOUT_PAYMENT=@WITH_OR_WITHOUT_PAYMENT&BILL_SUPPLIER_NAME=@BILL_SUPPLIER_NAME")]
        public string Schedule_Payment {
            get {
                return ((string)(this["Schedule_Payment"]));
            }
            set {
                this["Schedule_Payment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/opt_37.asmx/Account_Receivable?TRANSACTION_TYPE=@TRANSACTION_TYPE&FROM_YEAR_MONTH=@FROM_YEAR_MONTH&TO_YEAR_MONTH=@TO_YEAR_MONTH&FROM_STATUS_PLAN_DEPOSIT_YYMM=@FROM_STATUS_PLAN_DEPOSIT_YYMM&TO_STATUS_PLAN_DEPOSIT_YYMM=@TO_STATUS_PLAN_DEPOSIT_YYMM&FROM_STATUS_ACTUAL_DEPOSIT_DATE=@FROM_STATUS_ACTUAL_DEPOSIT_DATE&TO_STATUS_ACTUAL_DEPOSIT_DATE=@TO_STATUS_ACTUAL_DEPOSIT_DATE&DEPOSIT_RULE=@DEPOSIT_RULE&WITH_OR_WITHOUT_PAYMENT=@WITH_OR_WITHOUT_PAYMENT&BILL_SUPPLIER_NAME=@BILL_SUPPLIER_NAME")]
        public string Account_Receivable {
            get {
                return ((string)(this["Account_Receivable"]));
            }
            set {
                this["Account_Receivable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300, 640")]
        public global::System.Drawing.Size DefaultDimentions {
            get {
                return ((global::System.Drawing.Size)(this["DefaultDimentions"]));
            }
            set {
                this["DefaultDimentions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_3B.asmx/do_ManualAllocation?COMPANY_NO_BOX=@COMPANY_NO_" +
            "BOX&YEAR_MONTH=@YEAR_MONTH")]
        public string ManualAllocation {
            get {
                return ((string)(this["ManualAllocation"]));
            }
            set {
                this["ManualAllocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/opt_37.asmx/AllocationManualCompletion?ALLOCATE=@ALLOCATE&S" +
            "EQ_NO=@SEQ_NO&COMPANY_NO_BOX=@COMPANY_NO_BOX&YEAR_MONTH=@YEAR_MONTH&RECEIPT_ALLO" +
            "CATION_DATE=@RECEIPT_ALLOCATION_DATE&INVOICE_ALLOCATION_DATE=@INVOICE_ALLOCATION" +
            "_DATE")]
        public string ManualAllocationComplete {
            get {
                return ((string)(this["ManualAllocationComplete"]));
            }
            set {
                this["ManualAllocationComplete"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_jimugo.asmx/getJimugoMenu")]
        public string getJimugoMenu {
            get {
                return ((string)(this["getJimugoMenu"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RoyalBlue")]
        public global::System.Drawing.Color JimugoBgColor {
            get {
                return ((global::System.Drawing.Color)(this["JimugoBgColor"]));
            }
            set {
                this["JimugoBgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color jimugoForeColor {
            get {
                return ((global::System.Drawing.Color)(this["jimugoForeColor"]));
            }
            set {
                this["jimugoForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_CompanyCodeList.asmx/GetCompanyCodeList?COMPANY_" +
            "NO_BOX=@COMPANY_NO_BOX&COMPANY_NAME=@COMPANY_NAME&EMAIL=@EMAIL&OFFSET=@OFFSET&LI" +
            "MIT=@LIMIT")]
        public string GetCompanyCodeList {
            get {
                return ((string)(this["GetCompanyCodeList"]));
            }
            set {
                this["GetCompanyCodeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_CompanyCodeList.asmx/UpdateList")]
        public string UpdateCompanyCodeList {
            get {
                return ((string)(this["UpdateCompanyCodeList"]));
            }
            set {
                this["UpdateCompanyCodeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_CompanyCodeList.asmx/GetPassword")]
        public string GetPassword {
            get {
                return ((string)(this["GetPassword"]));
            }
            set {
                this["GetPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_CompanyCodeList.asmx/SendMail")]
        public string SendMail {
            get {
                return ((string)(this["SendMail"]));
            }
            set {
                this["SendMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageInfoRegistrationList.asmx/getUsageInformati" +
            "onRegistrationList?COMPANY_NO_BOX=@COMPANY_NO_BOX&COMPANY_NAME=@COMPANY_NAME&EDI" +
            "_ACCOUNT=@EDI_ACCOUNT&OFFSET=@OFFSET&LIMIT=@LIMIT")]
        public string GetUsageRegList {
            get {
                return ((string)(this["GetUsageRegList"]));
            }
            set {
                this["GetUsageRegList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageInfoRegistrationList.asmx/UpdateList")]
        public string UpdateUsageRegList {
            get {
                return ((string)(this["UpdateUsageRegList"]));
            }
            set {
                this["UpdateUsageRegList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageInfoRegistrationList.asmx/SettingCompleteMa" +
            "il")]
        public string SettingCompleteMail {
            get {
                return ((string)(this["SettingCompleteMail"]));
            }
            set {
                this["SettingCompleteMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_IssueQuotation.asmx/GetInitialData?COMPANY_NO_BO" +
            "X=@COMPANY_NO_BOX&REQ_SEQ=@REQ_SEQ")]
        public string GetIssueQuotationInitialData {
            get {
                return ((string)(this["GetIssueQuotationInitialData"]));
            }
            set {
                this["GetIssueQuotationInitialData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meiryo UI, 8.25pt")]
        public global::System.Drawing.Font jimugoFont {
            get {
                return ((global::System.Drawing.Font)(this["jimugoFont"]));
            }
            set {
                this["jimugoFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ClientCertificateList.asmx/GetClientCertificateL" +
            "ist?FY=@FY&COMPANY_NO_BOX=@COMPANY_NO_BOX&CLIENT_CERTIFICATE_NO=@CLIENT_CERTIFIC" +
            "ATE_NO&DISTRIBUTION_STATUS=@DISTRIBUTION_STATUS&OFFSET=@OFFSET&LIMIT=@LIMIT")]
        public string GetClientCertificateList {
            get {
                return ((string)(this["GetClientCertificateList"]));
            }
            set {
                this["GetClientCertificateList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ClientCertificateList.asmx/UpdateList")]
        public string UpdateClientCertificateList {
            get {
                return ((string)(this["UpdateClientCertificateList"]));
            }
            set {
                this["UpdateClientCertificateList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ClientCertificateList.asmx/SendMail")]
        public string SendMailClientCertificate {
            get {
                return ((string)(this["SendMailClientCertificate"]));
            }
            set {
                this["SendMailClientCertificate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageInfoRegistrationList.asmx/GetEDICandidates")]
        public string GetEDICandidates {
            get {
                return ((string)(this["GetEDICandidates"]));
            }
            set {
                this["GetEDICandidates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageInfoRegistrationList.asmx/ExtractEDIAutoInf" +
            "o?COMPANY_NO_BOX=@COMPANY_NO_BOX")]
        public string GetEDIAccountDetail {
            get {
                return ((string)(this["GetEDIAccountDetail"]));
            }
            set {
                this["GetEDIAccountDetail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/Jimugo/opt_CustomerMasterMaintenance.asmx/GetMaintenance?COMPANY_NO_BOX=@COMPANY_NO_BOX&COMPANY_NAME=@COMPANY_NAME&COMPANY_NAME_READING=@NAME_READING&EDI_ACCOUNT=@EDI_ACCOUNT&MAIL_ADDRESS=@MAIL_ADDRESS&CONTRACTOR=@CONTRACTOR&INVOICE=@INVOICE&SERVICE_DESK=@SERVICE_DESK&NOTIFICATION_DESTINATION=@NOTIFICATION_DESTINATION&OFFSET=@OFFSET&LIMIT=@LIMIT
")]
        public string GetCustomerMasterMaintenance {
            get {
                return ((string)(this["GetCustomerMasterMaintenance"]));
            }
            set {
                this["GetCustomerMasterMaintenance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_PurchaseOrder.asmx/Search?COMPANY_NO_BOX=@COMPAN" +
            "Y_NO_BOX&REQ_SEQ=@REQ_SEQ")]
        public string GetPurchaseOrdertem {
            get {
                return ((string)(this["GetPurchaseOrdertem"]));
            }
            set {
                this["GetPurchaseOrdertem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_PurchaseOrder.asmx/SubmitOrderRegister")]
        public string SubmitPurchaseOrder {
            get {
                return ((string)(this["SubmitPurchaseOrder"]));
            }
            set {
                this["SubmitPurchaseOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://localhost:6077/Jimugo/opt_UsageApplicationList.asmx/Search?COMPANY_NO_BOX=@COMPANY_NO_BOX&COMPANY_NAME=@COMPANY_NAME&CLOSE_FLG=@CLOSE_FLG&GD=@GD&REQUEST_STATUS=@REQUEST_STATUS&REQ_DATE_FROM=@REQ_DATE_FROM&REQ_DATE_TO=@REQ_DATE_TO&QUOTATION_DATE_FROM=@QUOTATION_DATE_FROM&QUOTATION_DATE_TO=@QUOTATION_DATE_TO&ORDER_DATE_FROM=@ORDER_DATE_FROM&ORDER_DATE_TO=@ORDER_DATE_TO&SYSTEM_SETTING_STATUS=@SYSTEM_SETTING_STATUS&OFFSET=@OFFSET&LIMIT=@LIMIT")]
        public string GetUsageApplicationList {
            get {
                return ((string)(this["GetUsageApplicationList"]));
            }
            set {
                this["GetUsageApplicationList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageApplicationList.asmx/Update")]
        public string UpdateUsageApplicationList {
            get {
                return ((string)(this["UpdateUsageApplicationList"]));
            }
            set {
                this["UpdateUsageApplicationList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageApplicationList.asmx/UpdateApplicationCance" +
            "l")]
        public string UpdateApplicationCancel {
            get {
                return ((string)(this["UpdateApplicationCancel"]));
            }
            set {
                this["UpdateApplicationCancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageApplicationList.asmx/ConfirmationRequest")]
        public string UpdateConfirmationRequest {
            get {
                return ((string)(this["UpdateConfirmationRequest"]));
            }
            set {
                this["UpdateConfirmationRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageApplicationList.asmx/ConfirmationComplete")]
        public string UpdateConfirmationComplete {
            get {
                return ((string)(this["UpdateConfirmationComplete"]));
            }
            set {
                this["UpdateConfirmationComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageApplicationList.asmx/GetSubProgramLists")]
        public string GetSubProgramLists {
            get {
                return ((string)(this["GetSubProgramLists"]));
            }
            set {
                this["GetSubProgramLists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_RegisterCompleteNotificationSending.asmx/Search?" +
            "COMPANY_NO_BOX=@COMPANY_NO_BOX")]
        public string GetScreenDataNotificatoinSending {
            get {
                return ((string)(this["GetScreenDataNotificatoinSending"]));
            }
            set {
                this["GetScreenDataNotificatoinSending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_RegisterCompleteNotificationSending.asmx/Preview" +
            "ProcessNotiSending")]
        public string PreviewNotification {
            get {
                return ((string)(this["PreviewNotification"]));
            }
            set {
                this["PreviewNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageChargeMaster.asmx/UpdateList")]
        public string UpdateUsageChargeMaster {
            get {
                return ((string)(this["UpdateUsageChargeMaster"]));
            }
            set {
                this["UpdateUsageChargeMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_UsageChargeMaster.asmx/GetUsageChargeMasterList?" +
            "CONTRACT_CODE=@CONTRACT_CODE&CONTRACT_NAME=@CONTRACT_NAME&OFFSET=@OFFSET&LIMIT=@" +
            "LIMIT")]
        public string GetUsageChargeMaster {
            get {
                return ((string)(this["GetUsageChargeMaster"]));
            }
            set {
                this["GetUsageChargeMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_RegisterCompleteNotificationSending.asmx/SendMai" +
            "lNotification")]
        public string SendMailNotification {
            get {
                return ((string)(this["SendMailNotification"]));
            }
            set {
                this["SendMailNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_IssueQuotation.asmx/DoPreview")]
        public string PreviewQuotation {
            get {
                return ((string)(this["PreviewQuotation"]));
            }
            set {
                this["PreviewQuotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_IssueQuotation.asmx/QuotationMailCreate")]
        public string QuotationMailCreate {
            get {
                return ((string)(this["QuotationMailCreate"]));
            }
            set {
                this["QuotationMailCreate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_CustomerMasterMaintenance.asmx/GetPopupScreenDat" +
            "a?COMPANY_NO_BOX=@COMPANY_NO_BOX&REQ_SEQ=@REQ_SEQ")]
        public string GetPopupScreenData {
            get {
                return ((string)(this["GetPopupScreenData"]));
            }
            set {
                this["GetPopupScreenData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_CustomerMasterMaintenance.asmx/Update")]
        public string UpdateCustomerMasterList {
            get {
                return ((string)(this["UpdateCustomerMasterList"]));
            }
            set {
                this["UpdateCustomerMasterList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ApplicationApproval.asmx/GetClientCertificateLis" +
            "t")]
        public string ApplicationApproval_GetInitialData {
            get {
                return ((string)(this["ApplicationApproval_GetInitialData"]));
            }
            set {
                this["ApplicationApproval_GetInitialData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ApplicationApproval.asmx/Disapprove")]
        public string ApplicationApproval_Disapprove {
            get {
                return ((string)(this["ApplicationApproval_Disapprove"]));
            }
            set {
                this["ApplicationApproval_Disapprove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ApplicationApproval.asmx/ApproveCancel")]
        public string ApplicationApproval_ApproveCancel {
            get {
                return ((string)(this["ApplicationApproval_ApproveCancel"]));
            }
            set {
                this["ApplicationApproval_ApproveCancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_ApplicationApproval.asmx/Approve")]
        public string ApplicationApproval_Approve {
            get {
                return ((string)(this["ApplicationApproval_Approve"]));
            }
            set {
                this["ApplicationApproval_Approve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_FileServices.asmx/GetTempFile")]
        public string GetTempFile {
            get {
                return ((string)(this["GetTempFile"]));
            }
            set {
                this["GetTempFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_MonthlySaleAggregationList.asmx/getMonthlySaleAg" +
            "gregationList")]
        public string getMonthlySaleAggregationlist {
            get {
                return ((string)(this["getMonthlySaleAggregationlist"]));
            }
            set {
                this["getMonthlySaleAggregationlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_FileServices.asmx/DeleteTempFile")]
        public string DeleteTempFile {
            get {
                return ((string)(this["DeleteTempFile"]));
            }
            set {
                this["DeleteTempFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/MonthlySaleComparisonList.asmx/getMonthlySaleCompari" +
            "sonList?YEAR_MONTH1=@strYYYMM1&YEAR_MONTH2=@strYYMM2&OFFSET=@OFFSET&LIMIT=@LIMIT" +
            "\r\n")]
        public string getMonthlySaleComparisonlist {
            get {
                return ((string)(this["getMonthlySaleComparisonlist"]));
            }
            set {
                this["getMonthlySaleComparisonlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_InvoiceList.asmx/GetInvoiceList?BILLING_DATE=@BI" +
            "LLING_DATE&OFFSET=@OFFSET&LIMIT=@LIMIT")]
        public string GetInvoiceList {
            get {
                return ((string)(this["GetInvoiceList"]));
            }
            set {
                this["GetInvoiceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_InvoiceList.asmx/CreateInvoiceData?YEAR_MONTH=@Y" +
            "EAR_MONTH")]
        public string CreateInvoiceData {
            get {
                return ((string)(this["CreateInvoiceData"]));
            }
            set {
                this["CreateInvoiceData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6077/Jimugo/opt_InvoiceList.asmx/CreateCSVFile?YEAR_MONTH=@YEAR_" +
            "MONTH")]
        public string GetInvoiceListForCSVCreate {
            get {
                return ((string)(this["GetInvoiceListForCSVCreate"]));
            }
            set {
                this["GetInvoiceListForCSVCreate"] = value;
            }
        }
    }
}
